name: Build and Release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                os: [darwin, linux, windows]
                arch: [386, amd64]
        steps:
            - uses: actions/checkout@v2

            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.22.3

            - name: Build and Archive
              run: |
                  mkdir -p goportscan/src
                  mv !(goportscan) goportscan/src
                  GOOS=${{ matrix.os }}
                  GOARCH=${{ matrix.arch }}
                  go build -o goportscan/portscan goportscan/src/*.go
                  os=${{ matrix.os }}
                  arch=${{ matrix.arch }}
                  zip -r portscan-${os}-${arch}.zip goportscan
              shell: bash

            - name: Upload Artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: portscan-${{ matrix.os }}-${{ matrix.arch }}
                  path: portscan-${{ matrix.os }}-${{ matrix.arch }}.zip

        outputs:
            matrix: ${{ toJSON(matrix) }}

    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Download Artifacts
              uses: actions/download-artifact@v2

            - name: Move Artifacts
              run: |
                  mv portscan-darwin-386/portscan-darwin-386.zip .
                  mv portscan-darwin-amd64/portscan-darwin-amd64.zip .
                  mv portscan-linux-386/portscan-linux-386.zip .
                  mv portscan-linux-amd64/portscan-linux-amd64.zip .
                  mv portscan-windows-386/portscan-windows-386.zip .
                  mv portscan-windows-amd64/portscan-windows-amd64.zip .

            - name: Create Tag
              id: create_tag
              run: |
                  TAG_NAME=$(date +'%Y%m%d%H%M%S')-release
                  git tag $TAG_NAME
                  echo "::set-output name=tag_name::$TAG_NAME"
              shell: bash

            - name: Upload Release Assets
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ steps.create_tag.outputs.tag_name }}
                  name: GoPortScan Release
                  files: |
                      portscan-darwin-386.zip
                      portscan-darwin-amd64.zip
                      portscan-linux-386.zip
                      portscan-linux-amd64.zip
                      portscan-windows-386.zip
                      portscan-windows-amd64.zip
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}