name: Build and Release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                os: [darwin, linux, windows]
        steps:
            - uses: actions/checkout@v2

            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.22.3

            - name: Build for ${{ matrix.os }}
              run: |
                  GOOS=${{ matrix.os }}
                  GOARCH=amd64  # Assuming amd64 architecture
                  # Ensure `cmd/goportscan` exists (adjust path if needed)
                  if [ ! -d "cmd/goportscan" ]; then
                      go mod download  # Download dependencies if missing
                  fi
                  go build -o goportscan ./cmd/goportscan

            - name: Create archive for ${{ matrix.os }}
              run: |
                  os=${{ matrix.os }}
                  arch=amd64  # Assuming amd64 architecture for all OSes
                  mkdir -p goportscan/src
                  mv goportscan goportscan/src
                  zip -r goportscan-${os}-${arch}.zip goportscan

            - name: Upload Release Assets
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ github.ref }}
                  name: ${{ matrix.os }} Build
                  files: goportscan-${{ matrix.os }}-amd64.zip
                  draft: false
                  prerelease: false
