name: Build and Release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                os: [darwin, linux, windows]
                arch: [386, amd64]
        steps:
            - uses: actions/checkout@v2

            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.22.3

            - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
              run: |
                  GOOS=${{ matrix.os }}
                  GOARCH=${{ matrix.arch }}
                  go build -o goportscan

            - name: Create archive for ${{ matrix.os }} ${{ matrix.arch }}
              run: |
                  os=${{ matrix.os }}
                  arch=${{ matrix.arch }}
                  mkdir -p goportscan/src
                  mv goportscan goportscan/src
                  zip -r goportscan-${os}-${arch}.zip goportscan

            - name: Upload Release Assets
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ github.ref }}
                  name: ${{ matrix.os }} ${{ matrix.arch }} Build
                  files: goportscan-${{ matrix.os }}-${{ matrix.arch }}.zip
                  draft: false
                  prerelease: false
