name: Build and Release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                os: [darwin, linux, windows]
                arch: [386, amd64]
        steps:
            - uses: actions/checkout@v2

            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.22.3

            - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
              run: |
                  GOOS=${{ matrix.os }}
                  GOARCH=${{ matrix.arch }}
                  go build -o goportscan/goportscan

            - name: Create archive for ${{ matrix.os }} ${{ matrix.arch }}
              run: |
                  os=${{ matrix.os }}
                  arch=${{ matrix.arch }}
                  mkdir -p goportscan/src
                  mv goportscan/goportscan goportscan/src
                  zip -r goportscan-${os}-${arch}.zip goportscan

            - name: Create Tag
              id: create_tag
              run: |
                  TAG_NAME=$(date +'%Y%m%d%H%M%S')-release
                  git tag $TAG_NAME
                  echo "::set-output name=tag_name::$TAG_NAME"
              shell: bash

            - name: Upload Release Assets
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ steps.create_tag.outputs.tag_name }}
                  name: ${{ matrix.os }} ${{ matrix.arch }} Build
                  files: goportscan-${{ matrix.os }}-${{ matrix.arch }}.zip
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}